version: "3"
services:
  node:
    build:
      context: .
      dockerfile: ./compose/nodejs/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      # - /home/node/app/node_modules
    ports:
      - "0.0.0.0:8080:${PORT:-8080}"
      # - "9090:${PORT:-8080}"
    command: "npm start"
    environment:
      # /run/docs/reference/container-contract
      PORT: ${PORT:-8080}
      K_SERVICE: portfolio
      K_REVISION: 0
      K_CONFIGURATION: portfolio