version: "2"
services:
  node:
    build:
      context: .
      dockerfile: ./compose/nodejs/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "8081:8081"
    command: "npm start"